### ISSUE TITLE
npm module

### ISSUE THREAD

**Issue by brianzelip** [colmtuite/bantamcss#13]
Hey looks like from your latest commit message that you might be trying unsuccessfully to publish Bantam CSS as a node module? If true it's pretty simple to do, you've got everything in place to do so (name and version in package.json).

I forked it and tried publishing it and everything worked. Here's a screenshot:
<img width="1438" alt="bantamcss-npm" src="https://cloud.githubusercontent.com/assets/3411019/12564137/a93c8a82-c37b-11e5-8b06-2875750f0339.png">

(I'll unpublish the module shortly so that you can have the namespace back.)

All you need to do is make sure you've created your npm username then run `npm publish` from the bantam dir on your machine, and you'll be good to go (see [this video](https://docs.npmjs.com/getting-started/publishing-npm-packages)). You'll want to update the npm package on future updates. See [this video about package versioning](https://docs.npmjs.com/getting-started/semantic-versioning) for details.

**Comment by colmtuite** [comment]
Thanks Brian, just got around to this now. I tweaked a few things, updated the version and got it published. I'm gonna work on it this week, should have it usable soon. Thanks for your help
