### ISSUE TITLE
Why did you decide to remove the prefixes from utility classes?

### ISSUE THREAD

**Issue by shanecarmody** [colmtuite/bantamcss#18]
I’m just curious to know the rationale 😃

**Comment by colmtuite** [comment]
I added the "u-" prefix based on Nicolas Gallagher's SuitCSS framework. I had an unhealthy obsession with Nicolas' work (Nicolas is the God of CSS) at the time and was likely to do anything he advocated.

Thinking about it now, I can't think of any real benefit to differentiating between utility classes and regular style classes. They both just apply styles to markup. In most cases, those styles are purely functional. So I don't see much point.

**Comment by shanecarmody** [comment]
Thanks for the explanation 👍 

I think it’s useful for developers when they want to know what they can remove and how it will affect the appearance. `u-` prefixed classes usually have one responsibility so one can remove them without worrying too much. I’m still torn between whether to use it or not.

I take inspiration from basscss, Tachyons and Harry Roberts’ blog. They have great ideas/advice.

**Comment by colmtuite** [comment]
The thing with Bantam though is, all classes have just a single responsibility. So you can remove any class without worrying how it might affect the markup. In that regard, I'm not sure if there's any merit to differentiating utility classes.

Utility classes actually often contain multiple declarations and in some cases, even child selectors. So there may be some merit to differentiating on that basis. Not sure though. Would like to hear some more solid arguments.
