### ISSUE TITLE
Reconsider 'Objects' folder name

### ISSUE THREAD

**Issue by colmtuite** [colmtuite/bantamcss#4]
Is 'objects' the most suitable name for this folder? The contents are not really 'objects', they're just single-purpose CSS classes. Perhaps there is a more suitable name?

**Comment by enociz** [comment]
If I am right, this has already been renamed to /spc

**Comment by colmtuite** [comment]
Correct. I'm not satisfied with it though.

I didn't like 'objects' because essentially, all of the files were CSS objects, not just those inside that folder.

I don't like 'spc' because it's not obvious what the abbreviation stands for. Also, many other folders contain single-purpose classes, not just the 'spc' folder.

Essentially, the framework is split into two categories:

1. Single-purpose classes that accept only fixed values (currently in /spc)
2. Single-purpose classes that accept custom values (currently in /theme)

I'm ok with /theme because it suggest personal customisation. However, I'd like to find a more suitable name for the /spc folder.

**Comment by enociz** [comment]
How about /fixed ? I guess it's semantic in a way.

**Comment by colmtuite** [comment]
To me, /fixed doesn't really communicate 'fixed value properties'. We could try /fixed-value-properties but that's so verbose and therefore difficult to scan. Also, I think seeing 'fixed value properties' makes you expect a folder for 'custom value properties'. But I think /theme is better than /custom-value-properties because I love the fact that 'theme' implies that this folder is the only folder in the framework that contains CSS which affects style.

Sorry for going on and on about a single folder name, but I think it's important to get these things right.

So yeah, I think whatever name we choose should satisfy these criteria:

1. Be short.
2. Be unabbreviated.
3. Communicate the nature of the folder's contents.
4. If possible, drop hints about the nature of other folder's contents.

**Comment by colmtuite** [comment]
Since I split up all the things into separate repos, there is only one folder necessary now, which is just /src.
